version: '3.1'

services:
  mysql-db:
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
    image: mysql:8.0.22
    ports:
      - 33060:3306
    volumes:
      - dj-walks-into-bar-mysql-data:/var/lib/mysql

  adminer:
    image: adminer
    ports:
      - 8080:8080
    volumes:
    - ./docker/adminer/adminer.css:/var/www/html/adminer.css

volumes:
  dj-walks-into-bar-mysql-data:
