"""Create table SimpleModel

Revision ID: f77ddcc85715
Revises:
Create Date: 2020-12-06 11:59:51.338552+00:00

"""
import sqlalchemy as sa
import sqlalchemy_utils

from alembic import op


# revision identifiers, used by Alembic.
from src.models import SimpleModel


revision = "f77ddcc85715"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "simplemodel",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("modified_at", sa.DateTime(), nullable=True),
        sa.Column("col_1", sa.String(length=100), nullable=True),
        sa.Column("col_2", sa.String(length=100), nullable=True),
        sa.Column("type", sqlalchemy_utils.types.choice.ChoiceType(SimpleModel.Type), nullable=True),
        sa.Column("value", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_simplemodel")),
        sa.UniqueConstraint("col_1", "col_2", name=op.f("uq_simplemodel_col_1")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("simplemodel")
    # ### end Alembic commands ###
