"""Create table SimpleMo

Revision ID: c4f8ca61426a
Revises: f77ddcc85715
Create Date: 2020-12-06 12:31:45.178720+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4f8ca61426a'
down_revision = 'f77ddcc85715'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
